import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import {IMAGE_DATA } from "../components/SliderData"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Photography Next</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
			</Head>
			<Hero
				heading="Capture Photography"
				message="This is an awesome site, created using NextJs"
			/>
			<Slider slides={IMAGE_DATA} />
		</>
	);
}
